### ISSUE TITLE
Change App name to FitKit  and add a proper icon 

### ISSUE THREAD

**Issue by ASVKVINAYAK** [ASVKVINAYAK/FitKit#1]
Change the app name to FitKit
Explore AndroidManifest File for more information

**Comment by Pritam0077** [comment]
ok i will try

**Comment by ASVKVINAYAK** [comment]
Change the app name and add an appropriate icon for the app @Pritam0077 work on it and update your progress in the discord section

**Comment by ASVKVINAYAK** [comment]
Nice work @Pritam0077  merged the PR
New issues will be coming so don't worry till then have any suggestions then create a issue.

**Comment by Pritam0077** [comment]
Ok😊
